{{ config(materialized='table') }}

SELECT
    RECLAMACAO.ANO,
    RECLAMACAO.TRIMESTRE,
    DM_CATEGORIA.ID_CAT,
    DM_TIPO.ID_IP,
    DM_INSTITUICAO.ID_INST,
    DM_INDICE.ID_IND,
    RECLAMACAO.QUANTIDADE_DE_RECLAMAES_REGULADAS_PROCEDENTES,
    RECLAMACAO.QUANTIDADE_DE_RECLAMAES_REGULADAS_OUTRAS,
    RECLAMACAO.QUANTIDADE_DE_RECLAMAES_NO_REGULADAS,
    RECLAMACAO.QUANTIDADE_TOTAL_DE_RECLAMAES,
    RECLAMACAO.QUANTIDADE_TOTAL_DE_CLIENTES_CCS_E_SCR,
    RECLAMACAO.QUANTIDADE_DE_CLIENTES_CCS,
    RECLAMACAO.QUANTIDADE_DE_CLIENTES_SCR,
    API_RECLAMACAO.VALORMAXIMO
FROM stage.file_csv_trusted as RECLAMACAO
LEFT JOIN stage.api_trusted as API_RECLAMACAO ON RECLAMACAO.CNPJ_IF = API_RECLAMACAO.CNPJ
LEFT JOIN stage.DM_CATEGORIA ON UPPER(RECLAMACAO.CATEGORIA) = UPPER(DM_CATEGORIA.CATEGORIA)
LEFT JOIN stage.DM_TIPO ON UPPER(RECLAMACAO.TIPO) = UPPER(DM_TIPO.TIPO)
LEFT JOIN stage.DM_INDICE ON UPPER(RECLAMACAO.NDICE) = UPPER(DM_INDICE.INDICE)
LEFT JOIN stage.DM_INSTITUICAO ON UPPER(RECLAMACAO.INSTITUIO_FINANCEIRA) = UPPER(DM_INSTITUICAO.INSTITUIO_FINANCEIRA) AND RECLAMACAO.CNPJ_IF = DM_INSTITUICAO.CNPJ_IF
WHERE TRIM(UPPER(API_RECLAMACAO.TIPOVALOR)) = 'REAL'
